"""Add event_type and event_key to Notification

Revision ID: 8bb334a5f92c
Revises: 984dbc5a2c4f
Create Date: 2026-09-17 03:26:10.427141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bb334a5f92c'
down_revision: Union[str, Sequence[str], None] = '984dbc5a2c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('event_type', sa.String(length=50), server_default='GENERAL', nullable=False))
    op.add_column('notifications', sa.Column('event_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'event_key')
    op.drop_column('notifications', 'event_type')
    # ### end Alembic commands ###
