"""add_civic_advisory_model

Revision ID: f4d37dcec9ab
Revises: 8bb334a5f92c
Create Date: 2026-09-17 11:50:16.631418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4d37dcec9ab'
down_revision: Union[str, Sequence[str], None] = '8bb334a5f92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civic_advisories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('ward_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='civic_advisory_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['pune_wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_civic_advisories_category_id'), 'civic_advisories', ['category_id'], unique=False)
    op.create_index(op.f('ix_civic_advisories_created_by'), 'civic_advisories', ['created_by'], unique=False)
    op.create_index(op.f('ix_civic_advisories_public_id'), 'civic_advisories', ['public_id'], unique=True)
    op.create_index(op.f('ix_civic_advisories_ward_id'), 'civic_advisories', ['ward_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_civic_advisories_ward_id'), table_name='civic_advisories')
    op.drop_index(op.f('ix_civic_advisories_public_id'), table_name='civic_advisories')
    op.drop_index(op.f('ix_civic_advisories_created_by'), table_name='civic_advisories')
    op.drop_index(op.f('ix_civic_advisories_category_id'), table_name='civic_advisories')
    op.drop_table('civic_advisories')
    op.execute("DROP TYPE IF EXISTS civic_advisory_status")
    # ### end Alembic commands ###
